export const findIcon = (item) => {
  switch (item) {
    case "colombia":
      return "./assets/countriesBackground/Colombia.png"
    case "italy":
      return "./assets/countriesBackground/Italy.png"
    case "southAfrica":
      return "./assets/countriesBackground/SouthAfrica.png"
    case "sweden":
      return "./assets/countriesBackground/Sweden.png"
    case "panama":
      return "./assets/countriesBackground/Panama.png"
    case "jamiaca":
      return "./assets/countriesBackground/Jamiaca.png"
    case "vietnam":
      return "./assets/countriesBackground/Vietnam.png"
    case "china":
      return "./assets/countriesBackground/China.png"
    case "haiti":
      return "./assets/countriesBackground/Haiti.png"
    case "zambia":
      return "./assets/countriesBackground/Zambia.png"
    case "nigeria":
      return "./assets/countriesBackground/Nigeria.png"
    case "ireland":
      return "./assets/countriesBackground/Ireland.png"
    case "philippines":
      return "./assets/countriesBackground/Philippines.png"
    case "norway":
      return "./assets/countriesBackground/Norway.png"
    case "newZealand":
      return "./assets/countriesBackground/NewZealand.png"
    case "argentina":
      return "./assets/countriesBackground/Argentina.png"
    case "australia":
      return "./assets/countriesBackground/Australia.png"
    case "belgium":
      return "./assets/countriesBackground/Belgium.png"

    case "brazil":
      return "./assets/countriesBackground/Brazil.png"

    case "cameroon":
      return "./assets/countriesBackground/Cameroon.png"

    case "canada":
      return "./assets/countriesBackground/Canada.png"

    case "costaRica":
      return "./assets/countriesBackground/CostaRica.png"

    case "croatia":
      return "./assets/countriesBackground/Croatia.png"

    case "denmark":
      return "./assets/countriesBackground/Denmark.png"

    case "ecuador":
      return "./assets/countriesBackground/Ecuador.png"

    case "england":
      return "./assets/countriesBackground/England.png"

    case "france":
      return "./assets/countriesBackground/France.png"

    case "germany":
      return "./assets/countriesBackground/Germany.png"

    case "ghana":
      return "./assets/countriesBackground/Ghana.png"

    case "iran":
      return "./assets/countriesBackground/Iran.png"

    case "japan":
      return "./assets/countriesBackground/Japan.png"

    case "mexico":
      return "./assets/countriesBackground/Mexico.png"

    case "morocco":
      return "./assets/countriesBackground/Morocco.png"

    case "netherlands":
      return "./assets/countriesBackground/Netherlands.png"

    case "poland":
      return "./assets/countriesBackground/Poland.png"

    case "portugal":
      return "./assets/countriesBackground/Portugal.png"

    case "qatar":
      return "./assets/countriesBackground/Qatar.png"

    case "saudiArabia":
      return "./assets/countriesBackground/SaudiArabia.png"

    case "senegal":
      return "./assets/countriesBackground/Senegal.png"

    case "serbia":
      return "./assets/countriesBackground/Serbia.png"

    case "southKorea":
      return "./assets/countriesBackground/SouthKorea.png"

    case "spain":
      return "./assets/countriesBackground/Spain.png"

    case "switzerland":
      return "./assets/countriesBackground/Switzerland.png"

    case "tunisia":
      return "./assets/countriesBackground/Tunisia.png"

    case "uruguay":
      return "./assets/countriesBackground/Uruguay.png"

    case "usa":
      return "./assets/countriesBackground/USA.png"

    case "wales":
      return "./assets/countriesBackground/Wales.png"
    case "newZealandFlag":
      return require("../assets/countriesFlag/NewZealand.png")
    case "zambiaFlag":
      return require("../assets/countriesFlag/Zambia.png")
    case "vietnamFlag":
      return require("../assets/countriesFlag/Vietnam.png")
    case "swedenFlag":
      return require("../assets/countriesFlag/Sweden.png")
    case "southAfricaFlag":
      return require("../assets/countriesFlag/SouthAfrica.png")
    case "philippinesFlag":
      return require("../assets/countriesFlag/Philippines.png")
    case "panamaFlag":
      return require("../assets/countriesFlag/Panama.png")
    case "nigeriaFlag":
      return require("../assets/countriesFlag/Nigeria.png")
    case "jamaicaFlag":
      return require("../assets/countriesFlag/Jamaica.png")
    case "italyFlag":
      return require("../assets/countriesFlag/Italy.png")
    case "irelandFlag":
      return require("../assets/countriesFlag/Ireland.png")
    case "haitiFlag":
      return require("../assets/countriesFlag/Haiti.png")
    case "colombiaFlag":
      return require("../assets/countriesFlag/Colombia.png")
    case "chinaFlag":
      return require("../assets/countriesFlag/China.png")
    case "argentinaFlag":
      return require("../assets/countriesFlag/Argentina.png")
    case "australiaFlag":
      return require("../assets/countriesFlag/Australia.png")
    case "belgiumFlag":
      return require("../assets/countriesFlag/Belgium.png")

    case "brazilFlag":
      return require("../assets/countriesFlag/Brazil.png")

    case "cameroonFlag":
      return require("../assets/countriesFlag/Cameroon.png")

    case "canadaFlag":
      return require("../assets/countriesFlag/Canada.png")

    case "costaRicaFlag":
      return require("../assets/countriesFlag/CostaRica.png")

    case "croatiaFlag":
      return require("../assets/countriesFlag/Croatia.png")

    case "denmarkFlag":
      return require("../assets/countriesFlag/Denmark.png")

    case "ecuadorFlag":
      return require("../assets/countriesFlag/Ecuador.png")

    case "englandFlag":
      return require("../assets/countriesFlag/England.png")

    case "franceFlag":
      return require("../assets/countriesFlag/France.png")

    case "germanyFlag":
      return require("../assets/countriesFlag/Germany.png")

    case "ghanaFlag":
      return require("../assets/countriesFlag/Ghana.png")

    case "iranFlag":
      return require("../assets/countriesFlag/Iran.png")

    case "japanFlag":
      return require("../assets/countriesFlag/Japan.png")

    case "mexicoFlag":
      return require("../assets/countriesFlag/Mexico.png")

    case "moroccoFlag":
      return require("../assets/countriesFlag/Morocco.png")

    case "netherlandsFlag":
      return require("../assets/countriesFlag/Netherlands.png")

    case "polandFlag":
      return require("../assets/countriesFlag/Poland.png")

    case "portugalFlag":
      return require("../assets/countriesFlag/Portugal.png")

    case "qatarFlag":
      return require("../assets/countriesFlag/Qatar.png")

    case "saudiArabiaFlag":
      return require("../assets/countriesFlag/SaudiArabia.png")

    case "senegalFlag":
      return require("../assets/countriesFlag/Senegal.png")

    case "serbiaFlag":
      return require("../assets/countriesFlag/Serbia.png")

    case "southKoreaFlag":
      return require("../assets/countriesFlag/SouthKorea.png")

    case "spainFlag":
      return require("../assets/countriesFlag/Spain.png")

    case "switzerlandFlag":
      return require("../assets/countriesFlag/Switzerland.png")

    case "tunisiaFlag":
      return require("../assets/countriesFlag/Tunisia.png")

    case "uruguayFlag":
      return require("../assets/countriesFlag/Uruguay.png")

    case "usaFlag":
      return require("../assets/countriesFlag/USA.png")

    case "walesFlag":
      return require("../assets/countriesFlag/Wales.png")

    /// Flags End

    case "world-series-bg":
      return require("../assets/world-series-bg.png")
    case "soccerTournamentCardBackground":
      return require("../assets/soccer2.png")
    case "hockeyTournamentCardBackground":
      return require("../assets/hockey2.png")
    case "baseBallTournamentCardBackground":
      return require("../assets/gSilhouette.png")
    case "logoEagle":
      return require("../assets/logoEagle.png")
    case "logoTiger":
      return require("../assets/logoTiger.png")
    case "logoRooster":
      return require("../assets/logoRooster.png")
    case "logoSnake":
      return require("../assets/logoSnake.png")
    case "logoWolf":
      return require("../assets/logoWolf.png")
    case "logoWhiteWolf":
      return require("../assets/logoWhiteWolf.png")
    case "logoRaccoon":
      return require("../assets/logoRaccoon.png")
    case "logoLion":
      return require("../assets/logoLion.png")
    case "logoGrinBear":
      return require("../assets/logoGrinBear.png")
    case "logoGorilla":
      return require("../assets/logoGorilla.png")
    case "logoFalcon":
      return require("../assets/logoFalcon.png")
    case "logoEagle":
      return require("../assets/logoEagle.png")
    case "logoRat":
      return require("../assets/logoRat.png")
    case "logoGoat":
      return require("../assets/logoGoat.png")
    case "logoRino":
      return require("../assets/logoRino.png")
    case "logoBear":
      return require("../assets/logoBear.png")
    case "logoDuck":
      return require("../assets/logoDuck.png")
    case "logoCroc":
      return require("../assets/logoCroc.png")
    case "logoBoar":
      return require("../assets/logoBoar.png")
    case "logoPython":
      return require("../assets/logoPython.png")
    case "logoShark":
      return require("../assets/logoShark.png")
    case "logoBat":
      return require("../assets/logoBat.png")
    case "logoPanda":
      return require("../assets/logoPanda.png")
    case "logoBulldog":
      return require("../assets/logoBulldog.png")
    case "logoHorse":
      return require("../assets/logoHorse.png")
    case "logoBull":
      return require("../assets/logoBull.png")
    case "logoElephant":
      return require("../assets/logoElephant.png")
    case "logoOwl":
      return require("../assets/logoOwl.png")
    case "logoHimalayanTiger":
      return require("../assets/logoHimalayanTiger.png")
    case "asset2":
      return require("../assets/asset2.png")
    case "asset3":
      return require("../assets/asset3.png")
    case "asset4":
      return require("../assets/asset4.png")
    case "asset5":
      return require("../assets/asset5.png")
    case "asset6":
      return require("../assets/asset6.png")
    case "asset7":
      return require("../assets/asset7.png")
    case "asset8":
      return require("../assets/asset8.png")
    case "asset9":
      return require("../assets/asset9.png")
    case "asset10":
      return require("../assets/asset10.png")
    case "asset11":
      return require("../assets/asset11.png")
    case "asset12":
      return require("../assets/asset12.png")
    case "asset13":
      return require("../assets/asset13.png")
    case "asset14":
      return require("../assets/asset14.png")
    case "asset15":
      return require("../assets/asset15.png")
    case "asset16":
      return require("../assets/asset16.png")
    case "asset17":
      return require("../assets/asset17.png")
    case "asset18":
      return require("../assets/asset18.png")
    case "asset19":
      return require("../assets/asset19.png")
    case "asset20":
      return require("../assets/asset20.png")
    case "asset21":
      return require("../assets/asset21.png")
    case "asset22":
      return require("../assets/asset22.png")

    case "drAhmad":
      return require("../assets/drAhmad.png")
    case "blendFC":
      return require("../assets/drAhmad.png")
    case "soccer":
      return require("../assets/greenSoccer.png")
    case "hockey":
      return require("../assets/blueHockey.png")
    case "baseBall":
      return require("../assets/redBaseBall.png")
    case "redStadium":
      return require("../assets/redStadium.png")
    case "blueStadium":
      return require("../assets/blueStadium.png")

    case "bear_colorless":
      return require("../assets/teams/bears/bear_colorless.png")
    case "bear_darkcyan":
      return require("../assets/teams/bears/bear_darkcyan.png")
    case "bear_forestgreen":
      return require("../assets/teams/bears/bear_forestgreen.png")
    case "bear_green":
      return require("../assets/teams/bears/bear_green.png")
    case "bear_grey":
      return require("../assets/teams/bears/bear_grey.png")
    case "bear_navyblue":
      return require("../assets/teams/bears/bear_navyblue.png")
    case "bear_orange":
      return require("../assets/teams/bears/bear_orange.png")
    case "bear_pink":
      return require("../assets/teams/bears/bear_pink.png")
    case "bear_purple":
      return require("../assets/teams/bears/bear_purple.png")
    case "bear_skyblue":
      return require("../assets/teams/bears/bear_skyblue.png")
    case "bear_tomato":
      return require("../assets/teams/bears/bear_tomato.png")
    case "bear_yellow":
      return require("../assets/teams/bears/bear_yellow.png")
    case "bengel_tiger_colorless":
      return require("../assets/teams/bengel_tigers/bengel_tiger_colorless.png")
    case "bengel_tiger_darkcyan":
      return require("../assets/teams/bengel_tigers/bengel_tiger_darkcyan.png")
    case "bengel_tiger_forestgreen":
      return require("../assets/teams/bengel_tigers/bengel_tiger_forestgreen.png")
    case "bengel_tiger_green":
      return require("../assets/teams/bengel_tigers/bengel_tiger_green.png")
    case "bengel_tiger_grey":
      return require("../assets/teams/bengel_tigers/bengel_tiger_grey.png")
    case "bengel_tiger_navyblue":
      return require("../assets/teams/bengel_tigers/bengel_tiger_navyblue.png")
    case "bengel_tiger_orange":
      return require("../assets/teams/bengel_tigers/bengel_tiger_orange.png")
    case "bengel_tiger_pink":
      return require("../assets/teams/bengel_tigers/bengel_tiger_pink.png")
    case "bengel_tiger_purple":
      return require("../assets/teams/bengel_tigers/bengel_tiger_purple.png")
    case "bengel_tiger_skyblue":
      return require("../assets/teams/bengel_tigers/bengel_tiger_skyblue.png")
    case "bengel_tiger_tomato":
      return require("../assets/teams/bengel_tigers/bengel_tiger_tomato.png")
    case "bengel_tiger_yellow":
      return require("../assets/teams/bengel_tigers/bengel_tiger_yellow.png")
    case "boar_colorless":
      return require("../assets/teams/boars/boar_colorless.png")
    case "boar_darkcyan":
      return require("../assets/teams/boars/boar_darkcyan.png")
    case "boar_forestgreen":
      return require("../assets/teams/boars/boar_forestgreen.png")
    case "boar_green":
      return require("../assets/teams/boars/boar_green.png")
    case "boar_grey":
      return require("../assets/teams/boars/boar_grey.png")
    case "boar_navyblue":
      return require("../assets/teams/boars/boar_navyblue.png")
    case "boar_orange":
      return require("../assets/teams/boars/boar_orange.png")
    case "boar_pink":
      return require("../assets/teams/boars/boar_pink.png")
    case "boar_purple":
      return require("../assets/teams/boars/boar_purple.png")
    case "boar_skyblue":
      return require("../assets/teams/boars/boar_skyblue.png")
    case "boar_tomato":
      return require("../assets/teams/boars/boar_tomato.png")
    case "boar_yellow":
      return require("../assets/teams/boars/boar_yellow.png")
    case "bull_colorless":
      return require("../assets/teams/bulls/bull_colorless.png")
    case "bull_darkcyan":
      return require("../assets/teams/bulls/bull_darkcyan.png")
    case "bull_forestgreen":
      return require("../assets/teams/bulls/bull_forestgreen.png")
    case "bull_green":
      return require("../assets/teams/bulls/bull_green.png")
    case "bull_grey":
      return require("../assets/teams/bulls/bull_grey.png")
    case "bull_navyblue":
      return require("../assets/teams/bulls/bull_navyblue.png")
    case "bull_orange":
      return require("../assets/teams/bulls/bull_orange.png")
    case "bull_pink":
      return require("../assets/teams/bulls/bull_pink.png")
    case "bull_purple":
      return require("../assets/teams/bulls/bull_purple.png")
    case "bull_skyblue":
      return require("../assets/teams/bulls/bull_skyblue.png")
    case "bull_tomato":
      return require("../assets/teams/bulls/bull_tomato.png")
    case "bull_yellow":
      return require("../assets/teams/bulls/bull_yellow.png")
    case "croc_colorless":
      return require("../assets/teams/crocs/croc_colorless.png")
    case "croc_darkcyan":
      return require("../assets/teams/crocs/croc_darkcyan.png")
    case "croc_forestgreen":
      return require("../assets/teams/crocs/croc_forestgreen.png")
    case "croc_green":
      return require("../assets/teams/crocs/croc_green.png")
    case "croc_grey":
      return require("../assets/teams/crocs/croc_grey.png")
    case "croc_navyblue":
      return require("../assets/teams/crocs/croc_navyblue.png")
    case "croc_orange":
      return require("../assets/teams/crocs/croc_orange.png")
    case "croc_pink":
      return require("../assets/teams/crocs/croc_pink.png")
    case "croc_purple":
      return require("../assets/teams/crocs/croc_purple.png")
    case "croc_skyblue":
      return require("../assets/teams/crocs/croc_skyblue.png")
    case "croc_tomato":
      return require("../assets/teams/crocs/croc_tomato.png")
    case "croc_yellow":
      return require("../assets/teams/crocs/croc_yellow.png")
    case "dog_colorless":
      return require("../assets/teams/dogs/dog_colorless.png")
    case "dog_darkcyan":
      return require("../assets/teams/dogs/dog_darkcyan.png")
    case "dog_forestgreen":
      return require("../assets/teams/dogs/dog_forestgreen.png")
    case "dog_green":
      return require("../assets/teams/dogs/dog_green.png")
    case "dog_navyblue":
      return require("../assets/teams/dogs/dog_navyblue.png")
    case "dog_orange":
      return require("../assets/teams/dogs/dog_orange.png")
    case "dog_purple":
      return require("../assets/teams/dogs/dog_purple.png")
    case "dog_skyblue":
      return require("../assets/teams/dogs/dog_skyblue.png")
    case "dog_tomato":
      return require("../assets/teams/dogs/dog_tomato.png")
    case "dog_yellow":
      return require("../assets/teams/dogs/dog_yellow.png")
    case "duck_colorless":
      return require("../assets/teams/ducks/duck_colorless.png")
    case "duck_darkcyan":
      return require("../assets/teams/ducks/duck_darkcyan.png")
    case "duck_forestgreen":
      return require("../assets/teams/ducks/duck_forestgreen.png")
    case "duck_green":
      return require("../assets/teams/ducks/duck_green.png")
    case "duck_grey":
      return require("../assets/teams/ducks/duck_grey.png")
    case "duck_navyblue":
      return require("../assets/teams/ducks/duck_navyblue.png")
    case "duck_orange":
      return require("../assets/teams/ducks/duck_orange.png")
    case "duck_pink":
      return require("../assets/teams/ducks/duck_pink.png")
    case "duck_purple":
      return require("../assets/teams/ducks/duck_purple.png")
    case "duck_skyblue":
      return require("../assets/teams/ducks/duck_skyblue.png")
    case "duck_tomato":
      return require("../assets/teams/ducks/duck_tomato.png")
    case "duck_yellow":
      return require("../assets/teams/ducks/duck_yellow.png")
    case "eagle_colorless":
      return require("../assets/teams/eagles/eagle_colorless.png")
    case "eagle_darkcyan":
      return require("../assets/teams/eagles/eagle_darkcyan.png")
    case "eagle_forestgreen":
      return require("../assets/teams/eagles/eagle_forestgreen.png")
    case "eagle_green":
      return require("../assets/teams/eagles/eagle_green.png")
    case "eagle_grey":
      return require("../assets/teams/eagles/eagle_grey.png")
    case "eagle_navyblue":
      return require("../assets/teams/eagles/eagle_navyblue.png")
    case "eagle_orange":
      return require("../assets/teams/eagles/eagle_orange.png")
    case "eagle_pink":
      return require("../assets/teams/eagles/eagle_pink.png")
    case "eagle_purple":
      return require("../assets/teams/eagles/eagle_purple.png")
    case "eagle_skyblue":
      return require("../assets/teams/eagles/eagle_skyblue.png")
    case "eagle_tomato":
      return require("../assets/teams/eagles/eagle_tomato.png")
    case "eagle_yellow":
      return require("../assets/teams/eagles/eagle_yellow.png")
    case "elephant_colorless":
      return require("../assets/teams/elephant/elephant_colorless.png")
    case "elephant_darkcyan":
      return require("../assets/teams/elephant/elephant_darkcyan.png")
    case "elephant_forestgreen":
      return require("../assets/teams/elephant/elephant_forestgreen.png")
    case "elephant_green":
      return require("../assets/teams/elephant/elephant_green.png")
    case "elephant_grey":
      return require("../assets/teams/elephant/elephant_grey.png")
    case "elephant_navyblue":
      return require("../assets/teams/elephant/elephant_navyblue.png")
    case "elephant_orange":
      return require("../assets/teams/elephant/elephant_orange.png")
    case "elephant_pink":
      return require("../assets/teams/elephant/elephant_pink.png")
    case "elephant_purple":
      return require("../assets/teams/elephant/elephant_purple.png")
    case "elephant_skyblue":
      return require("../assets/teams/elephant/elephant_skyblue.png")
    case "elephant_tomato":
      return require("../assets/teams/elephant/elephant_tomato.png")
    case "elephant_yellow":
      return require("../assets/teams/elephant/elephant_yellow.png")
    case "falcon_colorless":
      return require("../assets/teams/falcons/falcon_colorless.png")
    case "falcon_darkcyan":
      return require("../assets/teams/falcons/falcon_darkcyan.png")
    case "falcon_forestgreen":
      return require("../assets/teams/falcons/falcon_forestgreen.png")
    case "falcon_green":
      return require("../assets/teams/falcons/falcon_green.png")
    case "falcon_grey":
      return require("../assets/teams/falcons/falcon_grey.png")
    case "falcon_navyblue":
      return require("../assets/teams/falcons/falcon_navyblue.png")
    case "falcon_orange":
      return require("../assets/teams/falcons/falcon_orange.png")
    case "falcon_pink":
      return require("../assets/teams/falcons/falcon_pink.png")
    case "falcon_purple":
      return require("../assets/teams/falcons/falcon_purple.png")
    case "falcon_skyblue":
      return require("../assets/teams/falcons/falcon_skyblue.png")
    case "falcon_tomato":
      return require("../assets/teams/falcons/falcon_tomato.png")
    case "falcon_yellow":
      return require("../assets/teams/falcons/falcon_yellow.png")
    case "bird_colorless":
      return require("../assets/teams/flaming_bird/bird_colorless.png")
    case "bird_darkcyan":
      return require("../assets/teams/flaming_bird/bird_darkcyan.png")
    case "bird_forestgreen":
      return require("../assets/teams/flaming_bird/bird_forestgreen.png")
    case "bird_green":
      return require("../assets/teams/flaming_bird/bird_green.png")
    case "bird_grey":
      return require("../assets/teams/flaming_bird/bird_grey.png")
    case "bird_navyblue":
      return require("../assets/teams/flaming_bird/bird_navyblue.png")
    case "bird_orange":
      return require("../assets/teams/flaming_bird/bird_orange.png")
    case "bird_pink":
      return require("../assets/teams/flaming_bird/bird_pink.png")
    case "bird_purple":
      return require("../assets/teams/flaming_bird/bird_purple.png")
    case "bird_skyblue":
      return require("../assets/teams/flaming_bird/bird_skyblue.png")
    case "bird_tomato":
      return require("../assets/teams/flaming_bird/bird_tomato.png")
    case "bird_yellow":
      return require("../assets/teams/flaming_bird/bird_yellow.png")
    case "goat_colorless":
      return require("../assets/teams/goats/goat_colorless.png")
    case "goat_darkcyan":
      return require("../assets/teams/goats/goat_darkcyan.png")
    case "goat_forestgreen":
      return require("../assets/teams/goats/goat_forestgreen.png")
    case "goat_green":
      return require("../assets/teams/goats/goat_green.png")
    case "goat_grey":
      return require("../assets/teams/goats/goat_grey.png")
    case "goat_navyblue":
      return require("../assets/teams/goats/goat_navyblue.png")
    case "goat_orange":
      return require("../assets/teams/goats/goat_orange.png")
    case "goat_pink":
      return require("../assets/teams/goats/goat_pink.png")
    case "goat_purple":
      return require("../assets/teams/goats/goat_purple.png")
    case "goat_skyblue":
      return require("../assets/teams/goats/goat_skyblue.png")
    case "goat_tomato":
      return require("../assets/teams/goats/goat_tomato.png")
    case "goat_yellow":
      return require("../assets/teams/goats/goat_yellow.png")
    case "gorilla_colorless":
      return require("../assets/teams/gorillas/gorilla_colorless.png")
    case "gorilla_darkcyan":
      return require("../assets/teams/gorillas/gorilla_darkcyan.png")
    case "gorilla_forestgreen":
      return require("../assets/teams/gorillas/gorilla_forestgreen.png")
    case "gorilla_green":
      return require("../assets/teams/gorillas/gorilla_green.png")
    case "gorilla_grey":
      return require("../assets/teams/gorillas/gorilla_grey.png")
    case "gorilla_navyblue":
      return require("../assets/teams/gorillas/gorilla_navyblue.png")
    case "gorilla_orange":
      return require("../assets/teams/gorillas/gorilla_orange.png")
    case "gorilla_pink":
      return require("../assets/teams/gorillas/gorilla_pink.png")
    case "gorilla_purple":
      return require("../assets/teams/gorillas/gorilla_purple.png")
    case "gorilla_skyblue":
      return require("../assets/teams/gorillas/gorilla_skyblue.png")
    case "gorilla_tomato":
      return require("../assets/teams/gorillas/gorilla_tomato.png")
    case "gorilla_yellow":
      return require("../assets/teams/gorillas/gorilla_yellow.png")
    case "grin_bear_colorless":
      return require("../assets/teams/grin_bears/grin_bear_colorless.png")
    case "grin_bear_darkcyan":
      return require("../assets/teams/grin_bears/grin_bear_darkcyan.png")
    case "grin_bear_forestgreen":
      return require("../assets/teams/grin_bears/grin_bear_forestgreen.png")
    case "grin_bear_green":
      return require("../assets/teams/grin_bears/grin_bear_green.png")
    case "grin_bear_grey":
      return require("../assets/teams/grin_bears/grin_bear_grey.png")
    case "grin_bear_navyblue":
      return require("../assets/teams/grin_bears/grin_bear_navyblue.png")
    case "grin_bear_orange":
      return require("../assets/teams/grin_bears/grin_bear_orange.png")
    case "grin_bear_pink":
      return require("../assets/teams/grin_bears/grin_bear_pink.png")
    case "grin_bear_purple":
      return require("../assets/teams/grin_bears/grin_bear_purple.png")
    case "grin_bear_skyblue":
      return require("../assets/teams/grin_bears/grin_bear_skyblue.png")
    case "grin_bear_tomato":
      return require("../assets/teams/grin_bears/grin_bear_tomato.png")
    case "grin_bear_yellow":
      return require("../assets/teams/grin_bears/grin_bear_yellow.png")
    case "grizzly_bear_colorless":
      return require("../assets/teams/grizzly_bears/grizzly_bear_colorless.png")
    case "grizzly_bear_darkcyan":
      return require("../assets/teams/grizzly_bears/grizzly_bear_darkcyan.png")
    case "grizzly_bear_forestgreen":
      return require("../assets/teams/grizzly_bears/grizzly_bear_forestgreen.png")
    case "grizzly_bear_green":
      return require("../assets/teams/grizzly_bears/grizzly_bear_green.png")
    case "grizzly_bear_grey":
      return require("../assets/teams/grizzly_bears/grizzly_bear_grey.png")
    case "grizzly_bear_navyblue":
      return require("../assets/teams/grizzly_bears/grizzly_bear_navyblue.png")
    case "grizzly_bear_orange":
      return require("../assets/teams/grizzly_bears/grizzly_bear_orange.png")
    case "grizzly_bear_pink":
      return require("../assets/teams/grizzly_bears/grizzly_bear_pink.png")
    case "grizzly_bear_purple":
      return require("../assets/teams/grizzly_bears/grizzly_bear_purple.png")
    case "grizzly_bear_skyblue":
      return require("../assets/teams/grizzly_bears/grizzly_bear_skyblue.png")
    case "grizzly_bear_tomato":
      return require("../assets/teams/grizzly_bears/grizzly_bear_tomato.png")
    case "grizzly_bear_yellow":
      return require("../assets/teams/grizzly_bears/grizzly_bear_yellow.png")
    case "himalayan_tiger_colorless":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_colorless.png")
    case "himalayan_tiger_darkcyan":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_darkcyan.png")
    case "himalayan_tiger_forestgreen":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_forestgreen.png")
    case "himalayan_tiger_green":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_green.png")
    case "himalayan_tiger_grey":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_grey.png")
    case "himalayan_tiger_navyblue":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_navyblue.png")
    case "himalayan_tiger_orange":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_orange.png")
    case "himalayan_tiger_pink":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_pink.png")
    case "himalayan_tiger_purple":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_purple.png")
    case "himalayan_tiger_skyblue":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_skyblue.png")
    case "himalayan_tiger_tomato":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_tomato.png")
    case "himalayan_tiger_yellow":
      return require("../assets/teams/himalayan_tigers/himalayan_tiger_yellow.png")
    case "horse_colorless":
      return require("../assets/teams/horses/horse_colorless.png")
    case "horse_darkcyan":
      return require("../assets/teams/horses/horse_darkcyan.png")
    case "horse_forestgreen":
      return require("../assets/teams/horses/horse_forestgreen.png")
    case "horse_green":
      return require("../assets/teams/horses/horse_green.png")
    case "horse_grey":
      return require("../assets/teams/horses/horse_grey.png")
    case "horse_navyblue":
      return require("../assets/teams/horses/horse_navyblue.png")
    case "horse_orange":
      return require("../assets/teams/horses/horse_orange.png")
    case "horse_pink":
      return require("../assets/teams/horses/horse_pink.png")
    case "horse_purple":
      return require("../assets/teams/horses/horse_purple.png")
    case "horse_skyblue":
      return require("../assets/teams/horses/horse_skyblue.png")
    case "horse_tomato":
      return require("../assets/teams/horses/horse_tomato.png")
    case "horse_yellow":
      return require("../assets/teams/horses/horse_yellow.png")
    case "lion_colorless":
      return require("../assets/teams/lions/lion_colorless.png")
    case "lion_darkcyan":
      return require("../assets/teams/lions/lion_darkcyan.png")
    case "lion_forestgreen":
      return require("../assets/teams/lions/lion_forestgreen.png")
    case "lion_green":
      return require("../assets/teams/lions/lion_green.png")
    case "lion_grey":
      return require("../assets/teams/lions/lion_grey.png")
    case "lion_navyblue":
      return require("../assets/teams/lions/lion_navyblue.png")
    case "lion_orange":
      return require("../assets/teams/lions/lion_orange.png")
    case "lion_pink":
      return require("../assets/teams/lions/lion_pink.png")
    case "lion_purple":
      return require("../assets/teams/lions/lion_purple.png")
    case "lion_skyblue":
      return require("../assets/teams/lions/lion_skyblue.png")
    case "lion_tomato":
      return require("../assets/teams/lions/lion_tomato.png")
    case "lion_yellow":
      return require("../assets/teams/lions/lion_yellow.png")
    case "owl_colorless":
      return require("../assets/teams/owls/owl_colorless.png")
    case "owl_darkcyan":
      return require("../assets/teams/owls/owl_darkcyan.png")
    case "owl_forestgreen":
      return require("../assets/teams/owls/owl_forestgreen.png")
    case "owl_green":
      return require("../assets/teams/owls/owl_green.png")
    case "owl_navyblue":
      return require("../assets/teams/owls/owl_navyblue.png")
    case "owl_orange":
      return require("../assets/teams/owls/owl_orange.png")
    case "owl_purple":
      return require("../assets/teams/owls/owl_purple.png")
    case "owl_skyblue":
      return require("../assets/teams/owls/owl_skyblue.png")
    case "owl_tomato":
      return require("../assets/teams/owls/owl_tomato.png")
    case "owl_yellow":
      return require("../assets/teams/owls/owl_yellow.png")
    case "panda_colorless":
      return require("../assets/teams/pandas/panda_colorless.png")
    case "panda_darkcyan":
      return require("../assets/teams/pandas/panda_darkcyan.png")
    case "panda_forestgreen":
      return require("../assets/teams/pandas/panda_forestgreen.png")
    case "panda_green":
      return require("../assets/teams/pandas/panda_green.png")
    case "panda_grey":
      return require("../assets/teams/pandas/panda_grey.png")
    case "panda_navyblue":
      return require("../assets/teams/pandas/panda_navyblue.png")
    case "panda_orange":
      return require("../assets/teams/pandas/panda_orange.png")
    case "panda_pink":
      return require("../assets/teams/pandas/panda_pink.png")
    case "panda_purple":
      return require("../assets/teams/pandas/panda_purple.png")
    case "panda_skyblue":
      return require("../assets/teams/pandas/panda_skyblue.png")
    case "panda_tomato":
      return require("../assets/teams/pandas/panda_tomato.png")
    case "panda_yellow":
      return require("../assets/teams/pandas/panda_yellow.png")
    case "python_colorless":
      return require("../assets/teams/pythons/python_colorless.png")
    case "python_darkcyan":
      return require("../assets/teams/pythons/python_darkcyan.png")
    case "python_forestgreen":
      return require("../assets/teams/pythons/python_forestgreen.png")
    case "python_green":
      return require("../assets/teams/pythons/python_green.png")
    case "python_grey":
      return require("../assets/teams/pythons/python_grey.png")
    case "python_navyblue":
      return require("../assets/teams/pythons/python_navyblue.png")
    case "python_orange":
      return require("../assets/teams/pythons/python_orange.png")
    case "python_pink":
      return require("../assets/teams/pythons/python_pink.png")
    case "python_purple":
      return require("../assets/teams/pythons/python_purple.png")
    case "python_skyblue":
      return require("../assets/teams/pythons/python_skyblue.png")
    case "python_tomato":
      return require("../assets/teams/pythons/python_tomato.png")
    case "python_yellow":
      return require("../assets/teams/pythons/python_yellow.png")
    case "reccoon_colorless":
      return require("../assets/teams/raccoons/reccoon_colorless.png")
    case "reccoon_darkcyan":
      return require("../assets/teams/raccoons/reccoon_darkcyan.png")
    case "reccoon_forestgreen":
      return require("../assets/teams/raccoons/reccoon_forestgreen.png")
    case "reccoon_green":
      return require("../assets/teams/raccoons/reccoon_green.png")
    case "reccoon_grey":
      return require("../assets/teams/raccoons/reccoon_grey.png")
    case "reccoon_navyblue":
      return require("../assets/teams/raccoons/reccoon_navyblue.png")
    case "reccoon_orange":
      return require("../assets/teams/raccoons/reccoon_orange.png")
    case "reccoon_pink":
      return require("../assets/teams/raccoons/reccoon_pink.png")
    case "reccoon_purple":
      return require("../assets/teams/raccoons/reccoon_purple.png")
    case "reccoon_skyblue":
      return require("../assets/teams/raccoons/reccoon_skyblue.png")
    case "reccoon_tomato":
      return require("../assets/teams/raccoons/reccoon_tomato.png")
    case "reccoon_yellow":
      return require("../assets/teams/raccoons/reccoon_yellow.png")
    case "rat_colorless":
      return require("../assets/teams/rats/rat_colorless.png")
    case "rat_darkcyan":
      return require("../assets/teams/rats/rat_darkcyan.png")
    case "rat_forestgreen":
      return require("../assets/teams/rats/rat_forestgreen.png")
    case "rat_green":
      return require("../assets/teams/rats/rat_green.png")
    case "rat_navyblue":
      return require("../assets/teams/rats/rat_navyblue.png")
    case "rat_orange":
      return require("../assets/teams/rats/rat_orange.png")
    case "rat_purple":
      return require("../assets/teams/rats/rat_purple.png")
    case "rat_skyblue":
      return require("../assets/teams/rats/rat_skyblue.png")
    case "rat_tomato":
      return require("../assets/teams/rats/rat_tomato.png")
    case "rat_yellow":
      return require("../assets/teams/rats/rat_yellow.png")
    case "rhino_colorless":
      return require("../assets/teams/rhino/rhino_colorless.png")
    case "rhino_darkcyan":
      return require("../assets/teams/rhino/rhino_darkcyan.png")
    case "rhino_forestgreen":
      return require("../assets/teams/rhino/rhino_forestgreen.png")
    case "rhino_green":
      return require("../assets/teams/rhino/rhino_green.png")
    case "rhino_grey":
      return require("../assets/teams/rhino/rhino_grey.png")
    case "rhino_navyblue":
      return require("../assets/teams/rhino/rhino_navyblue.png")
    case "rhino_orange":
      return require("../assets/teams/rhino/rhino_orange.png")
    case "rhino_pink":
      return require("../assets/teams/rhino/rhino_pink.png")
    case "rhino_purple":
      return require("../assets/teams/rhino/rhino_purple.png")
    case "rhino_skyblue":
      return require("../assets/teams/rhino/rhino_skyblue.png")
    case "rhino_tomato":
      return require("../assets/teams/rhino/rhino_tomato.png")
    case "rhino_yellow":
      return require("../assets/teams/rhino/rhino_yellow.png")
    case "rooster_colorless":
      return require("../assets/teams/roosters/rooster_colorless.png")
    case "rooster_darkcyan":
      return require("../assets/teams/roosters/rooster_darkcyan.png")
    case "rooster_forestgreen":
      return require("../assets/teams/roosters/rooster_forestgreen.png")
    case "rooster_green":
      return require("../assets/teams/roosters/rooster_green.png")
    case "rooster_grey":
      return require("../assets/teams/roosters/rooster_grey.png")
    case "rooster_navyblue":
      return require("../assets/teams/roosters/rooster_navyblue.png")
    case "rooster_orange":
      return require("../assets/teams/roosters/rooster_orange.png")
    case "rooster_pink":
      return require("../assets/teams/roosters/rooster_pink.png")
    case "rooster_purple":
      return require("../assets/teams/roosters/rooster_purple.png")
    case "rooster_skyblue":
      return require("../assets/teams/roosters/rooster_skyblue.png")
    case "rooster_tomato":
      return require("../assets/teams/roosters/rooster_tomato.png")
    case "rooster_yellow":
      return require("../assets/teams/roosters/rooster_yellow.png")
    case "shark_colorless":
      return require("../assets/teams/sharks/shark_colorless.png")
    case "shark_darkcyan":
      return require("../assets/teams/sharks/shark_darkcyan.png")
    case "shark_forestgreen":
      return require("../assets/teams/sharks/shark_forestgreen.png")
    case "shark_green":
      return require("../assets/teams/sharks/shark_green.png")
    case "shark_grey":
      return require("../assets/teams/sharks/shark_grey.png")
    case "shark_navyblue":
      return require("../assets/teams/sharks/shark_navyblue.png")
    case "shark_orange":
      return require("../assets/teams/sharks/shark_orange.png")
    case "shark_pink":
      return require("../assets/teams/sharks/shark_pink.png")
    case "shark_purple":
      return require("../assets/teams/sharks/shark_purple.png")
    case "shark_skyblue":
      return require("../assets/teams/sharks/shark_skyblue.png")
    case "shark_tomato":
      return require("../assets/teams/sharks/shark_tomato.png")
    case "shark_yellow":
      return require("../assets/teams/sharks/shark_yellow.png")
    case "snack_colorless":
      return require("../assets/teams/snacks/snack_colorless.png")
    case "snack_darkcyan":
      return require("../assets/teams/snacks/snack_darkcyan.png")
    case "snack_forestgreen":
      return require("../assets/teams/snacks/snack_forestgreen.png")
    case "snack_green":
      return require("../assets/teams/snacks/snack_green.png")
    case "snack_grey":
      return require("../assets/teams/snacks/snack_grey.png")
    case "snack_navyblue":
      return require("../assets/teams/snacks/snack_navyblue.png")
    case "snack_orange":
      return require("../assets/teams/snacks/snack_orange.png")
    case "snack_pink":
      return require("../assets/teams/snacks/snack_pink.png")
    case "snack_purple":
      return require("../assets/teams/snacks/snack_purple.png")
    case "snack_skyblue":
      return require("../assets/teams/snacks/snack_skyblue.png")
    case "snack_tomato":
      return require("../assets/teams/snacks/snack_tomato.png")
    case "snack_yellow":
      return require("../assets/teams/snacks/snack_yellow.png")
    case "tiger_colorless":
      return require("../assets/teams/tiger/tiger_colorless.png")
    case "tiger_darkcyan":
      return require("../assets/teams/tiger/tiger_darkcyan.png")
    case "tiger_forestgreen":
      return require("../assets/teams/tiger/tiger_forestgreen.png")
    case "tiger_green":
      return require("../assets/teams/tiger/tiger_green.png")
    case "tiger_grey":
      return require("../assets/teams/tiger/tiger_grey.png")
    case "tiger_navyblue":
      return require("../assets/teams/tiger/tiger_navyblue.png")
    case "tiger_orange":
      return require("../assets/teams/tiger/tiger_orange.png")
    case "tiger_pink":
      return require("../assets/teams/tiger/tiger_pink.png")
    case "tiger_purple":
      return require("../assets/teams/tiger/tiger_purple.png")
    case "tiger_skyblue":
      return require("../assets/teams/tiger/tiger_skyblue.png")
    case "tiger_tomato":
      return require("../assets/teams/tiger/tiger_tomato.png")
    case "tiger_yellow":
      return require("../assets/teams/tiger/tiger_yellow.png")
    case "white_wolve_colorless":
      return require("../assets/teams/white_wolves/white_wolve_colorless.png")
    case "white_wolve_darkcyan":
      return require("../assets/teams/white_wolves/white_wolve_darkcyan.png")
    case "white_wolve_forestgreen":
      return require("../assets/teams/white_wolves/white_wolve_forestgreen.png")
    case "white_wolve_green":
      return require("../assets/teams/white_wolves/white_wolve_green.png")
    case "white_wolve_grey":
      return require("../assets/teams/white_wolves/white_wolve_grey.png")
    case "white_wolve_navyblue":
      return require("../assets/teams/white_wolves/white_wolve_navyblue.png")
    case "white_wolve_orange":
      return require("../assets/teams/white_wolves/white_wolve_orange.png")
    case "white_wolve_pink":
      return require("../assets/teams/white_wolves/white_wolve_pink.png")
    case "white_wolve_purple":
      return require("../assets/teams/white_wolves/white_wolve_purple.png")
    case "white_wolve_skyblue":
      return require("../assets/teams/white_wolves/white_wolve_skyblue.png")
    case "white_wolve_tomato":
      return require("../assets/teams/white_wolves/white_wolve_tomato.png")
    case "white_wolve_yellow":
      return require("../assets/teams/white_wolves/white_wolve_yellow.png")
    case "wolf_cat_colorless":
      return require("../assets/teams/wolf_cats/wolf_cat_colorless.png")
    case "wolf_cat_darkcyan":
      return require("../assets/teams/wolf_cats/wolf_cat_darkcyan.png")
    case "wolf_cat_forestgreen":
      return require("../assets/teams/wolf_cats/wolf_cat_forestgreen.png")
    case "wolf_cat_green":
      return require("../assets/teams/wolf_cats/wolf_cat_green.png")
    case "wolf_cat_grey":
      return require("../assets/teams/wolf_cats/wolf_cat_grey.png")
    case "wolf_cat_navyblue":
      return require("../assets/teams/wolf_cats/wolf_cat_navyblue.png")
    case "wolf_cat_orange":
      return require("../assets/teams/wolf_cats/wolf_cat_orange.png")
    case "wolf_cat_pink":
      return require("../assets/teams/wolf_cats/wolf_cat_pink.png")
    case "wolf_cat_purple":
      return require("../assets/teams/wolf_cats/wolf_cat_purple.png")
    case "wolf_cat_skyblue":
      return require("../assets/teams/wolf_cats/wolf_cat_skyblue.png")
    case "wolf_cat_tomato":
      return require("../assets/teams/wolf_cats/wolf_cat_tomato.png")
    case "wolf_cat_yellow":
      return require("../assets/teams/wolf_cats/wolf_cat_yellow.png")

    case "user1_asset1":
      return require("../assets/users/user1/asset1.png")
    case "user1_asset10":
      return require("../assets/users/user1/asset10.png")
    case "user1_asset11":
      return require("../assets/users/user1/asset11.png")
    case "user1_asset2":
      return require("../assets/users/user1/asset2.png")
    case "user1_asset3":
      return require("../assets/users/user1/asset3.png")
    case "user1_asset4":
      return require("../assets/users/user1/asset4.png")
    case "user1_asset5":
      return require("../assets/users/user1/asset5.png")
    case "user1_asset6":
      return require("../assets/users/user1/asset6.png")
    case "user1_asset7":
      return require("../assets/users/user1/asset7.png")
    case "user1_asset8":
      return require("../assets/users/user1/asset8.png")
    case "user1_asset9":
      return require("../assets/users/user1/asset9.png")
    case "user2_asset1":
      return require("../assets/users/user2/asset1.png")
    case "user2_asset10":
      return require("../assets/users/user2/asset10.png")
    case "user2_asset11":
      return require("../assets/users/user2/asset11.png")
    case "user2_asset2":
      return require("../assets/users/user2/asset2.png")
    case "user2_asset3":
      return require("../assets/users/user2/asset3.png")
    case "user2_asset4":
      return require("../assets/users/user2/asset4.png")
    case "user2_asset5":
      return require("../assets/users/user2/asset5.png")
    case "user2_asset6":
      return require("../assets/users/user2/asset6.png")
    case "user2_asset7":
      return require("../assets/users/user2/asset7.png")
    case "user2_asset8":
      return require("../assets/users/user2/asset8.png")
    case "user2_asset9":
      return require("../assets/users/user2/asset9.png")
    case "user3_asset1":
      return require("../assets/users/user3/asset1.png")
    case "user3_asset10":
      return require("../assets/users/user3/asset10.png")
    case "user3_asset11":
      return require("../assets/users/user3/asset11.png")
    case "user3_asset2":
      return require("../assets/users/user3/asset2.png")
    case "user3_asset3":
      return require("../assets/users/user3/asset3.png")
    case "user3_asset4":
      return require("../assets/users/user3/asset4.png")
    case "user3_asset5":
      return require("../assets/users/user3/asset5.png")
    case "user3_asset6":
      return require("../assets/users/user3/asset6.png")
    case "user3_asset7":
      return require("../assets/users/user3/asset7.png")
    case "user3_asset8":
      return require("../assets/users/user3/asset8.png")
    case "user3_asset9":
      return require("../assets/users/user3/asset9.png")
    case "user4_asset1":
      return require("../assets/users/user4/asset1.png")
    case "user4_asset10":
      return require("../assets/users/user4/asset10.png")
    case "user4_asset11":
      return require("../assets/users/user4/asset11.png")
    case "user4_asset2":
      return require("../assets/users/user4/asset2.png")
    case "user4_asset3":
      return require("../assets/users/user4/asset3.png")
    case "user4_asset4":
      return require("../assets/users/user4/asset4.png")
    case "user4_asset5":
      return require("../assets/users/user4/asset5.png")
    case "user4_asset6":
      return require("../assets/users/user4/asset6.pngcase "user4_asset6":
      return require("../assets/users/user4/asset6.png")
    case "user4_asset7":
      return require("../assets/users/user4/asset7.png")
    case "user4_asset8":
      return require("../assets/users/user4/asset8.png")
    case "user4_asset9":
      return require("../assets/users/user4/asset9.png")
    case "user5_asset1":
      return require("../assets/users/user5/asset1.png")
    case "user5_asset10":
      return require("../assets/users/user5/asset10.png")
    case "user5_asset11":
      return require("../assets/users/user5/asset11.png")
    case "user5_asset2":
      return require("../assets/users/user5/asset2.png")
    case "user5_asset3":
      return require("../assets/users/user5/asset3.png")
    case "user5_asset4":
      return require("../assets/users/user5/asset4.png")
    case "user5_asset5":
      return require("../assets/users/user5/asset5.png")
    case "user5_asset6":
      return require("../assets/users/user5/asset6.png")
    case "user5_asset7":
      return require("../assets/users/user5/asset7.png")
    case "user5_asset8":
      return require("../assets/users/user5/asset8.png")
    case "user5_asset9":
      return require("../assets/users/user5/asset9.png")
    case "user6_asset1":
      return require("../assets/users/user6/asset1.png")
    case "user6_asset10":
      return require("../assets/users/user6/asset10.png")
    case "user6_asset11":
      return require("../assets/users/user6/asset11.png")
    case "user6_asset2":
      return require("../assets/users/user6/asset2.png")
    case "user6_asset3":
      return require("../assets/users/user6/asset3.png")
    case "user6_asset4":
      return require("../assets/users/user6/asset4.png")
    case "user6_asset5":
      return require("../assets/users/user6/asset5.png")
    case "user6_asset6":
      return require("../assets/users/user6/asset6.png")
    case "user6_asset7":
      return require("../assets/users/user6/asset7.png")
    case "user6_asset8":
      return require("../assets/users/user6/asset8.png")
    case "user6_asset9":
      return require("../assets/users/user6/asset9.png")
    case "user7_asset1":
      return require("../assets/users/user7/asset1.png")
    case "user7_asset10":
      return require("../assets/users/user7/asset10.png")
    case "user7_asset11":
      return require("../assets/users/user7/asset11.png")
    case "user7_asset2":
      return require("../assets/users/user7/asset2.png")
    case "user7_asset3":
      return require("../assets/users/user7/asset3.png")
    case "user7_asset4":
      return require("../assets/users/user7/asset4.png")
    case "user7_asset5":
      return require("../assets/users/user7/asset5.png")
    case "user7_asset6":
      return require("../assets/users/user7/asset6.png")
    case "user7_asset7":
      return require("../assets/users/user7/asset7.png")
    case "user7_asset8":
      return require("../assets/users/user7/asset8.png")
    case "user7_asset9":
      return require("../assets/users/user7/asset9.png")
    case "user8_asset1":
      return require("../assets/users/user8/asset1.png")
    case "user8_asset2":
      return require("../assets/users/user8/asset2.png")
    case "user8_asset3":
      return require("../assets/users/user8/asset3.png")
    case "user8_asset4":
      return require("../assets/users/user8/asset4.png")
    case "user8_asset5":
      return require("../assets/users/user8/asset5.png")
    case "user8_asset6":
      return require("../assets/users/user8/asset6.png")
    case "user8_asset7":
      return require("../assets/users/user8/asset7.png")
    case "user8_asset8":
      return require("../assets/users/user8/asset8.png")
    case "user8_asset9":
      return require("../assets/users/user8/asset9.png")
    case "user9_asset1":
      return require("../assets/users/user9/asset1.png")
    case "user9_asset10":
      return require("../assets/users/user9/asset10.png")
    case "user9_asset11":
      return require("../assets/users/user9/asset11.png")
    case "user9_asset2":
      return require("../assets/users/user9/asset2.png")
    case "user9_asset3":
      return require("../assets/users/user9/asset3.png")
    case "user9_asset4":
      return require("../assets/users/user9/asset4.png")
    case "user9_asset5":
      return require("../assets/users/user9/asset5.png")
    case "user9_asset6":
      return require("../assets/users/user9/asset6.png")
    case "user9_asset7":
      return require("../assets/users/user9/asset7.png")
    case "user9_asset8":
      return require("../assets/users/user9/asset8.png")
    case "user9_asset9":
      return require("../assets/users/user9/asset9.png")
    case "user10_asset1":
      return require("../assets/users/user10/asset1.png")
    case "user10_asset10":
      return require("../assets/users/user10/asset10.png")
    case "user10_asset11":
      return require("../assets/users/user10/asset11.png")
    case "user10_asset2":
      return require("../assets/users/user10/asset2.png")
    case "user10_asset3":
      return require("../assets/users/user10/asset3.png")
    case "user10_asset4":
      return require("../assets/users/user10/asset4.png")
    case "user10_asset5":
      return require("../assets/users/user10/asset5.png")
    case "user10_asset6":
      return require("../assets/users/user10/asset6.png")
    case "user10_asset7":
      return require("../assets/users/user10/asset7.png")
    case "user10_asset8":
      return require("../assets/users/user10/asset8.png")
    case "user10_asset9":
      return require("../assets/users/user10/asset9.png")
    case "user11_asset1":
      return require("../assets/users/user11/asset1.png")
    case "user11_asset10":
      return require("../assets/users/user11/asset10.png")
    case "user11_asset11":
      return require("../assets/users/user11/asset11.png")
    case "user11_asset2":
      return require("../assets/users/user11/asset2.png")
    case "user11_asset3":
      return require("../assets/users/user11/asset3.png")
    case "user11_asset4":
      return require("../assets/users/user11/asset4.png")
    case "user11_asset5":
      return require("../assets/users/user11/asset5.png")
    case "user11_asset6":
      return require("../assets/users/user11/asset6.png")
    case "user11_asset7":
      return require("../assets/users/user11/asset7.png")
    case "user11_asset8":
      return require("../assets/users/user11/asset8.png")
    case "user11_asset9":
      return require("../assets/users/user11/asset9.png")
    case "user12_asset1":
      return require("../assets/users/user12/asset1.png")
    case "user12_asset10":
      return require("../assets/users/user12/asset10.png")
    case "user12_asset11":
      return require("../assets/users/user12/asset11.png")
    case "user12_asset2":
      return require("../assets/users/user12/asset2.png")
    case "user12_asset3":
      return require("../assets/users/user12/asset3.png")
    case "user12_asset4":
      return require("../assets/users/user12/asset4.png")
    case "user12_asset5":
      return require("../assets/users/user12/asset5.png")
    case "user12_asset6":
      return require("../assets/users/user12/asset6.png")
    case "user12_asset7":
      return require("../assets/users/user12/asset7.png")
    case "user12_asset8":
      return require("../assets/users/user12/asset8.png")
    case "user12_asset9":
      return require("../assets/users/user12/asset9.png")
    case "user13_asset1":
      return require("../assets/users/user13/asset1.png")
    case "user13_asset10":
      return require("../assets/users/user13/asset10.png")
    case "user13_asset11":
      return require("../assets/users/user13/asset11.png")
    case "user13_asset2":
      return require("../assets/users/user13/asset2.png")
    case "user13_asset3":
      return require("../assets/users/user13/asset3.png")
    case "user13_asset4":
      return require("../assets/users/user13/asset4.png")
    case "user13_asset5":
      return require("../assets/users/user13/asset5.png")
    case "user13_asset6":
      return require("../assets/users/user13/asset6.png")
    case "user13_asset7":
      return require("../assets/users/user13/asset7.png")
    case "user13_asset8":
      return require("../assets/users/user13/asset8.png")
    case "user13_asset9":
      return require("../assets/users/user13/asset9.png")
    case "user14_asset1":
      return require("../assets/users/user14/asset1.png")
    case "user14_asset10":
      return require("../assets/users/user14/asset10.png")
    case "user14_asset11":
      return require("../assets/users/user14/asset11.png")
    case "user14_asset2":
      return require("../assets/users/user14/asset2.png")
    case "user14_asset3":
      return require("../assets/users/user14/asset3.png")
    case "user14_asset4":
      return require("../assets/users/user14/asset4.png")
    case "user14_asset5":
      return require("../assets/users/user14/asset5.png")
    case "user14_asset6":
      return require("../assets/users/user14/asset6.png")
    case "user14_asset7":
      return require("../assets/users/user14/asset7.png")
    case "user14_asset8":
      return require("../assets/users/user14/asset8.png")
    case "user14_asset9":
      return require("../assets/users/user14/asset9.png")
    case "user15_asset1":
      return require("../assets/users/user15/asset1.png")
    case "user15_asset10":
      return require("../assets/users/user15/asset10.png")
    case "user15_asset11":
      return require("../assets/users/user15/asset11.png")
    case "user15_asset2":
      return require("../assets/users/user15/asset2.png")
    case "user15_asset3":
      return require("../assets/users/user15/asset3.png")
    case "user15_asset4":
      return require("../assets/users/user15/asset4.png")
    case "user15_asset5":
      return require("../assets/users/user15/asset5.png")
    case "user15_asset6":
      return require("../assets/users/user15/asset6.png")
    case "user15_asset7":
      return require("../assets/users/user15/asset7.png")
    case "user15_asset8":
      return require("../assets/users/user15/asset8.png")
    case "user15_asset9":
      return require("../assets/users/user15/asset9.png")
    case "user16_asset1":
      return require("../assets/users/user16/asset1.png")
    case "user16_asset10":
      return require("../assets/users/user16/asset10.png")
    case "user16_asset11":
      return require("../assets/users/user16/asset11.png")
    case "user16_asset2":
      return require("../assets/users/user16/asset2.png")
    case "user16_asset3":
      return require("../assets/users/user16/asset3.png")
    case "user16_asset4":
      return require("../assets/users/user16/asset4.png")
    case "user16_asset5":
      return require("../assets/users/user16/asset5.png")
    case "user16_asset6":
      return require("../assets/users/user16/asset6.png")
    case "user16_asset7":
      return require("../assets/users/user16/asset7.png")
    case "user16_asset8":
      return require("../assets/users/user16/asset8.png")
    case "user16_asset9":
      return require("../assets/users/user16/asset9.png")
    case "user17_asset1":
      return require("../assets/users/user17/asset1.png")
    case "user17_asset10":
      return require("../assets/users/user17/asset10.png")
    case "user17_asset11":
      return require("../assets/users/user17/asset11.png")
    case "user17_asset2":
      return require("../assets/users/user17/asset2.png")
    case "user17_asset3":
      return require("../assets/users/user17/asset3.png")
    case "user17_asset4":
      return require("../assets/users/user17/asset4.png")
    case "user17_asset5":
      return require("../assets/users/user17/asset5.png")
    case "user17_asset6":
      return require("../assets/users/user17/asset6.png")
    case "user17_asset7":
      return require("../assets/users/user17/asset7.png")
    case "user17_asset8":
      return require("../assets/users/user17/asset8.png")
    case "user17_asset9":
      return require("../assets/users/user17/asset9.png")
    case "user18_asset1":
      return require("../assets/users/user18/asset1.png")
    case "user18_asset10":
      return require("../assets/users/user18/asset10.png")
    case "user18_asset11":
      return require("../assets/users/user18/asset11.png")
    case "user18_asset2":
      return require("../assets/users/user18/asset2.png")
    case "user18_asset3":
      return require("../assets/users/user18/asset3.png")
    case "user18_asset4":
      return require("../assets/users/user18/asset4.png")
    case "user18_asset5":
      return require("../assets/users/user18/asset5.png")
    case "user18_asset6":
      return require("../assets/users/user18/asset6.png")
    case "user18_asset7":
      return require("../assets/users/user18/asset7.png")
    case "user18_asset8":
      return require("../assets/users/user18/asset8.png")
    case "user18_asset9":
      return require("../assets/users/user18/asset9.png")
    case "user19_asset1":
      return require("../assets/users/user19/asset1.png")
    case "user19_asset10":
      return require("../assets/users/user19/asset10.png")
    case "user19_asset11":
      return require("../assets/users/user19/asset11.png")
    case "user19_asset2":
      return require("../assets/users/user19/asset2.png")
    case "user19_asset3":
      return require("../assets/users/user19/asset3.png")
    case "user19_asset4":
      return require("../assets/users/user19/asset4.png")
    case "user19_asset5":
      return require("../assets/users/user19/asset5.png")
    case "user19_asset6":
      return require("../assets/users/user19/asset6.png")
    case "user19_asset7":
      return require("../assets/users/user19/asset7.png")
    case "user19_asset8":
      return require("../assets/users/user19/asset8.png")
    case "user19_asset9":
      return require("../assets/users/user19/asset9.png")
    case "user20_asset1":
      return require("../assets/users/user20/asset1.png")
    case "user20_asset10":
      return require("../assets/users/user20/asset10.png")
    case "user20_asset11":
      return require("../assets/users/user20/asset11.png")
    case "user20_asset2":
      return require("../assets/users/user20/asset2.png")
    case "user20_asset3":
      return require("../assets/users/user20/asset3.png")
    case "user20_asset4":
      return require("../assets/users/user20/asset4.png")
    case "user20_asset5":
      return require("../assets/users/user20/asset5.png")
    case "user20_asset6":
      return require("../assets/users/user20/asset6.png")
    case "user20_asset7":
      return require("../assets/users/user20/asset7.png")
    case "user20_asset8":
      return require("../assets/users/user20/asset8.png")
    case "user20_asset9":
      return require("../assets/users/user20/asset9.png")
    case "user21_asset1":
      return require("../assets/users/user21/asset1.png")
    case "user21_asset10":
      return require("../assets/users/user21/asset10.png")
    case "user21_asset11":
      return require("../assets/users/user21/asset11.png")
    case "user21_asset2":
      return require("../assets/users/user21/asset2.png")
    case "user21_asset3":
      return require("../assets/users/user21/asset3.png")
    case "user21_asset4":
      return require("../assets/users/user21/asset4.png")
    case "user21_asset5":
      return require("../assets/users/user21/asset5.png")
    case "user21_asset6":
      return require("../assets/users/user21/asset6.png")
    case "user21_asset7":
      return require("../assets/users/user21/asset7.png")
    case "user21_asset8":
      return require("../assets/users/user21/asset8.png")
    case "user21_asset9":
      return require("../assets/users/user21/asset9.png")

    // bases
    case "astrodome_darkblue":
      return require("../assets/base_icons/astrodome/astrodome_darkblue.png")
    case "astrodome_deeppink":
      return require("../assets/base_icons/astrodome/astrodome_deeppink.png")
    case "astrodome_deepskyblue":
      return require("../assets/base_icons/astrodome/astrodome_deepskyblue.png")
    case "astrodome_forestgreen":
      return require("../assets/base_icons/astrodome/astrodome_forestgreen.png")
    case "astrodome_frenchblue":
      return require("../assets/base_icons/astrodome/astrodome_frenchblue.png")
    case "astrodome_gold":
      return require("../assets/base_icons/astrodome/astrodome_gold.png")
    case "astrodome_gray":
      return require("../assets/base_icons/astrodome/astrodome_gray.png")
    case "astrodome_lavender":
      return require("../assets/base_icons/astrodome/astrodome_lavender.png")
    case "astrodome_mediumpurple":
      return require("../assets/base_icons/astrodome/astrodome_mediumpurple.png")
    case "astrodome_paleturquoise":
      return require("../assets/base_icons/astrodome/astrodome_paleturquoise.png")
    case "astrodome_yellow":
      return require("../assets/base_icons/astrodome/astrodome_yellow.png")
    case "cake_base_darkblue":
      return require("../assets/base_icons/cake_base/cake_base_darkblue.png")
    case "cake_base_deeppink":
      return require("../assets/base_icons/cake_base/cake_base_deeppink.png")
    case "cake_base_deepskyblue":
      return require("../assets/base_icons/cake_base/cake_base_deepskyblue.png")
    case "cake_base_forestgreen":
      return require("../assets/base_icons/cake_base/cake_base_forestgreen.png")
    case "cake_base_frenchblue":
      return require("../assets/base_icons/cake_base/cake_base_frenchblue.png")
    case "cake_base_gold":
      return require("../assets/base_icons/cake_base/cake_base_gold.png")
    case "cake_base_grey":
      return require("../assets/base_icons/cake_base/cake_base_grey.png")
    case "cake_base_lavender":
      return require("../assets/base_icons/cake_base/cake_base_lavender.png")
    case "cake_base_mediumpurple":
      return require("../assets/base_icons/cake_base/cake_base_mediumpurple.png")
    case "cake_base_paleturquoise":
      return require("../assets/base_icons/cake_base/cake_base_paleturquoise.png")
    case "cake_base_yellow":
      return require("../assets/base_icons/cake_base/cake_base_yellow.png")
    case "center_base_darkblue":
      return require("../assets/base_icons/center_base/center_base_darkblue.png")
    case "center_base_deeppink":
      return require("../assets/base_icons/center_base/center_base_deeppink.png")
    case "center_base_deepskyblue":
      return require("../assets/base_icons/center_base/center_base_deepskyblue.png")
    case "center_base_forestgreen":
      return require("../assets/base_icons/center_base/center_base_forestgreen.png")
    case "center_base_frenchblue":
      return require("../assets/base_icons/center_base/center_base_frenchblue.png")
    case "center_base_gold":
      return require("../assets/base_icons/center_base/center_base_gold.png")
    case "center_base_grey":
      return require("../assets/base_icons/center_base/center_base_grey.png")
    case "center_base_lavender":
      return require("../assets/base_icons/center_base/center_base_lavender.png")
    case "center_base_mediumpurple":
      return require("../assets/base_icons/center_base/center_base_mediumpurple.png")
    case "center_base_paleturquoise":
      return require("../assets/base_icons/center_base/center_base_paleturquoise.png")
    case "center_base_yellow":
      return require("../assets/base_icons/center_base/center_base_yellow.png")

    case "rock_darkblue":
      return require("../assets/base_icons/rock/rock_darkblue.png")
    case "rock_deeppink":
      return require("../assets/base_icons/rock/rock_deeppink.png")
    case "rock_deepskyblue":
      return require("../assets/base_icons/rock/rock_deepskyblue.png")
    case "rock_forestgreen":
      return require("../assets/base_icons/rock/rock_forestgreen.png")
    case "rock_frenchblue":
      return require("../assets/base_icons/rock/rock_frenchblue.png")
    case "rock_gold":
      return require("../assets/base_icons/rock/rock_gold.png")
    case "rock_grey":
      return require("../assets/base_icons/rock/rock_grey.png")
    case "rock_lavender":
      return require("../assets/base_icons/rock/rock_lavender.png")
    case "rock_mediumpurple":
      return require("../assets/base_icons/rock/rock_mediumpurple.png")
    case "rock_paleturquoise":
      return require("../assets/base_icons/rock/rock_paleturquoise.png")
    case "rock_yellow":
      return require("../assets/base_icons/rock/rock_yellow.png")
    case "rock_open_darkblue":
      return require("../assets/base_icons/rock_open/rock_open_darkblue.png")
    case "rock_open_deeppink":
      return require("../assets/base_icons/rock_open/rock_open_deeppink.png")
    case "rock_open_deepskyblue":
      return require("../assets/base_icons/rock_open/rock_open_deepskyblue.png")
    case "rock_open_forestgreen":
      return require("../assets/base_icons/rock_open/rock_open_forestgreen.png")
    case "rock_open_frenchblue":
      return require("../assets/base_icons/rock_open/rock_open_frenchblue.png")
    case "rock_open_gold":
      return require("../assets/base_icons/rock_open/rock_open_gold.png")
    case "rock_open_grey":
      return require("../assets/base_icons/rock_open/rock_open_grey.png")
    case "rock_open_lavender":
      return require("../assets/base_icons/rock_open/rock_open_lavender.png")
    case "rock_open_mediumpurple":
      return require("../assets/base_icons/rock_open/rockmediumpurple":
      return require("../assets/base_icons/rock_open/rock_open_mediumpurple.png")
    case "rock_open_paleturquoise":
      return require("../assets/base_icons/rock_open/rock_open_paleturquoise.png")
    case "rock_open_yellow":
      return require("../assets/base_icons/rock_open/rock_open_yellow.png")
    case "roof_open_darkblue":
      return require("../assets/base_icons/roof_open/roof_open_darkblue.png")
    case "roof_open_deeppink":
      return require("../assets/base_icons/roof_open/roof_open_deeppink.png")
    case "roof_open_deepskyblue":
      return require("../assets/base_icons/roof_open/roof_open_deepskyblue.png")
    case "roof_open_forestgreen":
      return require("../assets/base_icons/roof_open/roof_open_forestgreen.png")
    case "roof_open_frenchblue":
      return require("../assets/base_icons/roof_open/roof_open_frenchblue.png")
    case "roof_open_gold":
      return require("../assets/base_icons/roof_open/roof_open_gold.png")
    case "roof_open_grey":
      return require("../assets/base_icons/roof_open/roof_open_grey.png")
    case "roof_open_lavender":
      return require("../assets/base_icons/roof_open/roof_open_lavender.png")
    case "roof_open_mediumpurple":
      return require("../assets/base_icons/roof_open/roof_open_mediumpurple.png")
    case "roof_open_paleturquoise":
      return require("../assets/base_icons/roof_open/roof_open_paleturquoise.png")
    case "roof_open_yellow":
      return require("../assets/base_icons/roof_open/roof_open_yellow.png")
    case "superdome_darkblue":
      return require("../assets/base_icons/superdome/superdome_darkblue.png")
    case "superdome_deeppink":
      return require("../assets/base_icons/superdome/superdome_deeppink.png")
    case "superdome_deepskyblue":
      return require("../assets/base_icons/superdome/superdome_deepskyblue.png")
    case "superdome_forestgreen":
      return require("../assets/base_icons/superdome/superdome_forestgreen.png")
    case "superdome_frenchblue":
      return require("../assets/base_icons/superdome/superdome_frenchblue.png")
    case "superdome_gold":
      return require("../assets/base_icons/superdome/superdome_gold.png")
    case "superdome_grey":
      return require("../assets/base_icons/superdome/superdome_grey.png")
    case "superdome_lavender":
      return require("../assets/base_icons/superdome/superdome_lavender.png")
    case "superdome_mediumpurple":
      return require("../assets/base_icons/superdome/superdome_mediumpurple.png")
    case "superdome_paleturquoise":
      return require("../assets/base_icons/superdome/superdome_paleturquoise.png")
    case "superdome_yellow":
      return require("../assets/base_icons/superdome/superdome_yellow.png")

    case "diamond_darkblue":
      return require("../assets/base_icons/diamond/diamond_darkblue.png")
    case "diamond_deeppink":
      return require("../assets/base_icons/diamond/diamond_deeppink.png")
    case "diamond_deepskyblue":
      return require("../assets/base_icons/diamond/diamond_deepskyblue.png")
    case "diamond_forestgreen":
      return require("../assets/base_icons/diamond/diamond_forestgreen.png")
    case "diamond_frenchblue":
      return require("../assets/base_icons/diamond/diamond_frenchblue.png")
    case "diamond_gold":
      return require("../assets/base_icons/diamond/diamond_gold.png")
    case "diamond_grey":
      return require("../assets/base_icons/diamond/diamond_grey.png")
    case "diamond_lavender":
      return require("../assets/base_icons/diamond/diamond_lavender.png")
    case "diamond_mediumpurple":
      return require("../assets/base_icons/diamond/diamond_mediumpurple.png")
    case "diamond_turquoise":
      return require("../assets/base_icons/diamond/diamond_turquoise.png")
    case "diamond_yellow":
      return require("../assets/base_icons/diamond/diamond_yellow.png")
    case "dome_darkblue":
      return require("../assets/base_icons/dome/dome_darkblue.png")
    case "dome_deeppink":
      return require("../assets/base_icons/dome/dome_deeppink.png")
    case "dome_deepskyblue":
      return require("../assets/base_icons/dome/dome_deepskyblue.png")
    case "dome_forestgreen":
      return require("../assets/base_icons/dome/dome_forestgreen.png")
    case "dome_frenchblue":
      return require("../assets/base_icons/dome/dome_frenchblue.png")
    case "dome_gold":
      return require("../assets/base_icons/dome/dome_gold.png")
    case "dome_grey":
      return require("../assets/base_icons/dome/dome_grey.png")
    case "dome_lavender":
      return require("../assets/base_icons/dome/dome_lavender.png")
    case "dome_mediumpurple":
      return require("../assets/base_icons/dome/dome_mediumpurple.png")
    case "dome_paleturquoise":
      return require("../assets/base_icons/dome/dome_paleturquoise.png")
    case "dome_yellow":
      return require("../assets/base_icons/dome/dome_yellow.png")
    case "dome_light_darkblue":
      return require("../assets/base_icons/dome_light/dome_light_darkblue.png")
    case "dome_light_deeppink":
      return require("../assets/base_icons/dome_light/dome_light_deeppink.png")
    case "dome_light_deepskyblue":
      return require("../assets/base_icons/dome_light/dome_light_deepskyblue.png")
    case "dome_light_forestgreen":
      return require("../assets/base_icons/dome_light/dome_light_forestgreen.png")
    case "dome_light_frenchblue":
      return require("../assets/base_icons/dome_light/dome_light_frenchblue.png")
    case "dome_light_gold":
      return require("../assets/base_icons/dome_light/dome_light_gold.png")
    case "dome_light_grey":
      return require("../assets/base_icons/dome_light/dome_light_grey.png")
    case "dome_light_lavender":
      return require("../assets/base_icons/dome_light/dome_light_lavender.png")
    case "dome_light_mediumpurple":
      return require("../assets/base_icons/dome_light/dome_light_mediumpurple.png")
    case "dome_light_paleturquoise":
      return require("../assets/base_icons/dome_light/dome_light_paleturquoise.png")
    case "dome_light_yellow":
      return require("../assets/base_icons/dome_light/dome_light_yellow.png")
    case "floodlights_darkblue":
      return require("../assets/base_icons/floodlights/floodlights_darkblue.png")
    case "floodlights_deeppink":
      return require("../assets/base_icons/floodlights/floodlights_deeppink.png")
    case "floodlights_deepskyblue":
      return require("../assets/base_icons/floodlights/floodlights_deepskyblue.png")
    case "floodlights_forestgreen":
      return require("../assets/base_icons/floodlights/floodlights_forestgreen.png")
    case "floodlights_frenchblue":
      return require("../assets/base_icons/floodlights/floodlights_frenchblue.png")
    case "floodlights_gold":
      return require("../assets/base_icons/floodlights/floodlights_gold.png")
    case "floodlights_grey":
      return require("../assets/base_icons/floodlights/floodlights_grey.png")
    case "floodlights_lavender":
      return require("../assets/base_icons/floodlights/floodlights_lavender.png")
    case "floodlights_mediumpurple":
      return require("../assets/base_icons/floodlights/floodlights_mediumpurple.png")
    case "floodlights_paleturquoise":
      return require("../assets/base_icons/floodlights/floodlights_paleturquoise.png")
    case "floodlights_yellow":
      return require("../assets/base_icons/floodlights/floodlights_yellow.png")
    case "1v":
      return require("../assets/1v.png")
    case "2v":
      return require("../assets/2v.png")
    case "3v":
      return require("../assets/3v.png")
    case "soccerColor":
      require("../assets/soccerColorCircle.png")
    case "hockeyColor":
      require("../assets/hockeyColorCircle.png")
    case "baseballColor":
      require("../assets/baseballColorCircle.png")
    case "hexagon":
      return require("../assets/rotatedHex.png")
    case "hexagonPlus":
      return "./assets/hexaplus.png"
    case "hexagonPlusClear":
      return "./assets/hexaplusclear.png"
    default:
      return "./assets/logoOwl.png"
  }
}

export default findIcon

